### ISSUE TITLE
document SIGHASH type

### ISSUE THREAD

**Issue by benma** [JoinMarket-Org/JoinMarket-Docs#3]
Hi

Reading through https://github.com/JoinMarket-Org/JoinMarket-Docs/blob/master/High-level-design.md#transactions, it is not obvious what kind of sighash flags are used in the coinjoin transactions. I assume it's the standard `SIGHASH_ALL`. Is that true, or are there other sighash configurations in use?

Would be great to document it either way.

Thanks

**Comment by AdamISZ** [comment]
It is indeed SIGHASH_ALL only, so not mentioning it is somewhat defensible, although I agree better to be explicit. Back in the day there were a bunch of discussions about using SIGHASH_ACP|SIGHASH_NONE for more exotic styles of coinjoin but none of the ideas really seemed to work at all.

**Comment by benma** [comment]
Thanks for the clarification.
